// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Patterns",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Patterns",
            targets: ["AppModule"],
            bundleIdentifier: "me.ankithreddy.Patterns",
            teamIdentifier: "JGYJLKYVH5",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "This app requires camera access to detect hand poses"),
                .microphone(purposeString: "The app wil use microphone to control the app"),
                .speechRecognition(purposeString: "My app understands the commands user tells for app control")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("Resources/MNISTClassifier.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)